BIBSYSDEV/nva-datamodel-java

.gitignore
src/main/java/no/unit/nva/model/Approval.java
src/main/java/no/unit/nva/model/ApprovalStatus.java
src/main/java/no/unit/nva/model/ApprovalsBody.java
src/main/java/no/unit/nva/model/Grant.java
src/main/java/no/unit/nva/model/Project.java
src/main/java/no/unit/nva/model/Publication.java
src/main/java/no/unit/nva/model/ResearchProject.java
src/main/resources/publicationFrame.json
src/test/java/no/unit/nva/model/PublicationTest.java
src/test/java/no/unit/nva/model/util/ContextUtilTest.java
src/test/java/no/unit/nva/model/util/OrgNumberMapperTest.java

As it turns out, project is more complex that at first imagined, while we actually need a reference, we also need to be able to serialise data about projects, including:
- Grants
- Approvals

Add support for projects, and associated grants, approvals

---

src/main/java/no/unit/nva/model/EntityDescription.java
src/main/resources/publicationFrame.json
src/test/java/no/unit/nva/model/PublicationTest.java

- Added field metadata source to EntityDescription (this is the lowest level where we use this data)
- Updated equals, hash
- Updated test helper methods
- Updated JSON-LD frame

Add support for metadataSource

---

src/main/java/no/unit/nva/model/EntityDescription.java
src/main/resources/publicationFrame.json
src/test/java/no/unit/nva/model/PublicationTest.java

Remove publicationType

---

src/main/java/no/unit/nva/model/NullSeries.java
src/main/java/no/unit/nva/model/Series.java
src/main/java/no/unit/nva/model/SeriesImpl.java
src/main/java/no/unit/nva/model/contexttypes/Book.java
src/main/java/no/unit/nva/model/contexttypes/Journal.java
src/main/java/no/unit/nva/model/contexttypes/PublicationContext.java
src/main/java/no/unit/nva/model/contexttypes/Report.java
src/main/java/no/unit/nva/model/contexttypes/SerialPublication.java
src/main/java/no/unit/nva/model/contexttypes/utils/IssnUtil.java
src/test/java/no/unit/nva/model/contexttypes/BookTest.java
src/test/resources/book.json.template

- Create interface SerialPublication
- Create Utility for IssnChecking
- Add Report

Np 923 create type report add report

---

src/main/java/no/unit/nva/model/NullSeries.java
src/main/java/no/unit/nva/model/Series.java
src/main/java/no/unit/nva/model/SeriesImpl.java
src/main/java/no/unit/nva/model/contexttypes/Book.java
src/main/java/no/unit/nva/model/contexttypes/PublicationContext.java
src/test/java/no/unit/nva/model/contexttypes/BookTest.java
src/test/resources/book.json.template

In this PR, because Report is simply a subtype of Book, we need Series:
- Add series concept, including
- Series, including Title and Number
- NullSeries object for cases where a Book is not part a series
- Refactor tests

Add series support to Book

---

src/main/java/no/unit/nva/model/contexttypes/Book.java
src/main/java/no/unit/nva/model/contexttypes/PublicationContext.java
src/test/java/no/unit/nva/model/contexttypes/BookTest.java
src/test/resources/book.json.template

- Add Class Book
- Add BookTest
- update JSON subtype handling in PublicationContext

Add type book, tests and update PublicationContext JSON subtype handling

---

src/main/java/no/unit/nva/model/contexttypes/Book.java
src/test/java/no/unit/nva/model/contexttypes/BookTest.java

- refactor variable name isbns -> isbnList
- expose isbnList to mapper

Change isnbs -> isbnList, isbn -> isbnList

---

src/main/java/no/unit/nva/model/instancetypes/DegreePhd.java
src/test/java/no/unit/nva/model/instancetypes/DegreePhdTest.java

Add degree phd

---

src/main/java/no/unit/nva/model/instancetypes/DegreeMaster.java
src/main/java/no/unit/nva/model/instancetypes/DegreePhd.java
src/test/java/no/unit/nva/model/instancetypes/DegreeMasterTest.java
src/test/java/no/unit/nva/model/instancetypes/DegreePhdTest.java

- Add degreemaster
- Add degreemastertest

Add degree master

---

src/main/java/no/unit/nva/model/instancetypes/DegreeBachelor.java
src/main/java/no/unit/nva/model/instancetypes/DegreeMaster.java
src/main/java/no/unit/nva/model/instancetypes/DegreePhd.java
src/main/java/no/unit/nva/model/instancetypes/PublicationInstance.java
src/test/java/no/unit/nva/model/instancetypes/BookAnthologyTest.java
src/test/java/no/unit/nva/model/instancetypes/BookInstanceTest.java
src/test/java/no/unit/nva/model/instancetypes/DegreeBachelorTest.java
src/test/java/no/unit/nva/model/instancetypes/DegreeMasterTest.java
src/test/java/no/unit/nva/model/instancetypes/DegreePhdTest.java

- Add DegreeBachelor
- Add DegreeBachelorTest
- Refactor book-instance-related tests to use common superclass

Np 944 create publication instance bachelor

---

src/main/java/no/unit/nva/model/util/OrgNumberMapper.java

Unit NO919477822
Fjellhaug Internasjonale Høgskole NO973259415
Universitetet i Oslo NO971035854
Norsk institutt for naturforskning NO950037687
NORCE Norwegian Research Centre AS NO987375639
SINTEF AS NO919303808
NTNU NO974767880
BI NO971228865
10:38
Har Unit, Fjellhaug
Ole Ludvig Grøndahl  10:39 AM
Fjellhaug https://api.cristin.no/v2/institutions/258
10:39
UiO https://api.cristin.no/v2/institutions/185 (edited) 
10:40
NTNU https://api.cristin.no/v2/institutions/194
10:42
NINA https://api.cristin.no/v2/institutions/7511?lang=nb
10:43
NORCE https://api.cristin.no/v2/institutions/2057
10:45
SINTEF https://api.cristin.no/v2/institutions/7401 (Probably)
10:45
BI https://api.cristin.no/v2/institutions/158 (edited) 
10:46
UNIT https://api.cristin.no/v2/institutions/20202

Added missing orgNumbers to mapper

---

src/main/java/no/unit/nva/model/Contributor.java
src/test/java/no/unit/nva/model/ContributorTest.java

- Add tests to complete coverage of branches

Add parametrized test to complete coverage

---

src/main/java/no/unit/nva/model/File.java
src/test/java/no/unit/nva/model/FileTest.java

- Make fields in File final
- Cover all branches

Make fields final, improve test coverage

---

build.gradle
src/main/java/no/unit/nva/model/Reference.java
src/main/java/no/unit/nva/model/contexttypes/Chapter.java
src/main/java/no/unit/nva/model/contexttypes/Degree.java
src/main/java/no/unit/nva/model/instancetypes/JournalLeader.java
src/main/java/no/unit/nva/model/instancetypes/PublicationInstance.java
src/test/java/no/unit/nva/ModelTest.java
src/test/java/no/unit/nva/PublicationTest.java
src/test/java/no/unit/nva/model/ContributorTest.java
src/test/java/no/unit/nva/model/FileTest.java
src/test/java/no/unit/nva/model/ModelTest.java
src/test/java/no/unit/nva/model/PublicationJournalArticleTest.java
src/test/java/no/unit/nva/model/contexttypes/BookTest.java
src/test/java/no/unit/nva/model/contexttypes/ChapterTest.java
src/test/java/no/unit/nva/model/contexttypes/DegreeTest.java
src/test/java/no/unit/nva/model/contexttypes/ReportTest.java
src/test/java/no/unit/nva/model/instancetypes/InstanceTest.java
src/test/java/no/unit/nva/model/util/PublicationGenerator.java

- Added end-to-end round-tripping of all variants of model
- Changed some features in model that were inconsistent
- Removed fields openAccess and Peer reviewed where irrelevant
- Gradually moving away from Publication generator

Np 1013 prelogue refactoring

---

src/main/java/no/unit/nva/model/instancetypes/NonPeerReviewed.java
src/main/java/no/unit/nva/model/instancetypes/NonPeerReviewedMonograph.java
src/main/java/no/unit/nva/model/instancetypes/NonPeerReviewedPaper.java
src/main/java/no/unit/nva/model/instancetypes/PeerReviewed.java
src/main/java/no/unit/nva/model/instancetypes/PeerReviewedMonograph.java
src/main/java/no/unit/nva/model/instancetypes/PeerReviewedPaper.java
src/main/java/no/unit/nva/model/instancetypes/journal/JournalArticle.java
src/test/java/no/unit/nva/JsonHandlingTest.java
src/test/java/no/unit/nva/model/ModelTest.java
src/test/java/no/unit/nva/model/instancetypes/InstanceTest.java
src/test/java/no/unit/nva/model/instancetypes/PublicationInstanceTest.java
src/test/java/no/unit/nva/model/instancetypes/book/BookAnthologyTest.java
src/test/java/no/unit/nva/model/instancetypes/book/BookMonographTest.java
src/test/java/no/unit/nva/model/instancetypes/chapter/ChapterArticleTest.java
src/test/java/no/unit/nva/model/instancetypes/degree/DegreeBachelorTest.java
src/test/java/no/unit/nva/model/instancetypes/degree/DegreeMasterTest.java
src/test/java/no/unit/nva/model/instancetypes/degree/DegreePhdTest.java
src/test/resources/publication_instance_pages.json

- Fix testing of JSON
- Add PeerReviewed class to mirror NonPeerReviewed

Np 1013 restucture package membership fix tests

---

src/test/java/no/unit/nva/model/contexttypes/utils/IssnUtilTest.java

Add issn util test

---

src/main/java/no/unit/nva/PublicationMapper.java
src/main/java/no/unit/nva/WithFlags.java
src/main/java/no/unit/nva/api/CreatePublicationRequest.java
src/main/java/no/unit/nva/api/PublicationResponse.java
src/main/java/no/unit/nva/api/UpdatePublicationRequest.java
src/test/java/no/unit/nva/PublicationMapperTest.java

Hm, suggestions for a better solution?

Added doiRequested flag to PublicationResponse

---

config/checkstyle/checkstyle-author.xsl
config/checkstyle/checkstyle-frames.xsl
config/checkstyle/checkstyle-simple.xsl
config/checkstyle/checkstyle-text.xsl
config/checkstyle/checkstyle.xml
documentation/BookAnthology.json
documentation/BookMonograph.json
documentation/ChapterArticle.json
documentation/DegreeBachelor.json
documentation/DegreeMaster.json
documentation/DegreePhd.json
documentation/JournalArticle.json
documentation/JournalLeader.json
documentation/JournalLetter.json
documentation/JournalReview.json
documentation/JournalShortCommunication.json
documentation/ReportPolicy.json
documentation/ReportResearch.json
documentation/ReportWorkingPaper.json
src/main/java/no/unit/nva/model/DoiRequest.java
src/main/java/no/unit/nva/model/DoiRequestMessage.java
src/test/java/no/unit/nva/model/DoiRequestMessageTest.java
src/test/java/no/unit/nva/model/DoiRequestTest.java
src/test/java/no/unit/nva/model/util/PublicationGenerator.java

All JSON doc files were updated automatically thought tests. I commited the changes because I added doiRequestMessages in DoiRequest in Publication and I do not know which JSON docs were affected.

Np 1384 doi requests with messages

---

src/main/java/no/unit/nva/model/Publication.java

Related to https://github.com/BIBSYSDEV/nva-datamodel-java/pull/78#discussion_r490752898

Use qualified imports for java.util.Objects

---

documentation/BookAnthology.json
documentation/BookMonograph.json
documentation/ChapterArticle.json
documentation/DegreeBachelor.json
documentation/DegreeMaster.json
documentation/DegreePhd.json
documentation/JournalArticle.json
documentation/JournalLeader.json
documentation/JournalLetter.json
documentation/JournalReview.json
documentation/JournalShortCommunication.json
documentation/ReportPolicy.json
documentation/ReportResearch.json
documentation/ReportWorkingPaper.json
documentation/schema.yaml

Related to https://github.com/BIBSYSDEV/nva-datamodel-java/pull/78

Generated documentation updated from NP-1046 updateDoiRequestStatus

---

documentation/BookAnthology.json
documentation/BookMonograph.json
documentation/ChapterArticle.json
documentation/DegreeBachelor.json
documentation/DegreeMaster.json
documentation/DegreePhd.json
documentation/JournalArticle.json
documentation/JournalLeader.json
documentation/JournalLetter.json
documentation/JournalReview.json
documentation/JournalShortCommunication.json
documentation/ReportPolicy.json
documentation/ReportResearch.json
documentation/ReportWorkingPaper.json
documentation/schema.yaml
src/main/java/no/unit/nva/model/DoiRequest.java
src/main/java/no/unit/nva/model/Publication.java
src/test/java/no/unit/nva/model/DoiRequestMessageTest.java
src/test/java/no/unit/nva/model/DoiRequestTest.java
src/test/java/no/unit/nva/model/ModelTest.java
src/test/java/no/unit/nva/model/util/PublicationGenerator.java

New property doiRequest.modifiedDate, set to same value as publication.modifiedDate upon doiRequest status changes,

Np 1698 doi request modified date

---

documentation/FeatureArticle.json
documentation/schema.yaml
src/main/java/no/unit/nva/model/instancetypes/PublicationInstance.java
src/main/java/no/unit/nva/model/instancetypes/journal/FeatureArticle.java
src/test/java/no/unit/nva/PublicationTest.java
src/test/java/no/unit/nva/model/ModelTest.java

Adds another subtype of Article where the only real difference is the name of the type…this should indicate something to us, I think.

Add FeatureArticle

---

documentation/JournalCorrigendum.json
documentation/schema.yaml
src/main/java/no/unit/nva/model/instancetypes/PublicationInstance.java
src/main/java/no/unit/nva/model/instancetypes/journal/JournalCorrigendum.java
src/test/java/no/unit/nva/PublicationTest.java
src/test/java/no/unit/nva/model/ModelTest.java

Adds the Instance type Journal corrigendum, I don't think it adds anything new at all, just a new named type

Add journal corrigendum

---

documentation/OtherStudentWork.json
documentation/schema.yaml
src/main/java/no/unit/nva/model/instancetypes/PublicationInstance.java
src/main/java/no/unit/nva/model/instancetypes/degree/OtherStudentWork.java
src/test/java/no/unit/nva/PublicationTest.java
src/test/java/no/unit/nva/model/ModelTest.java

Add other student work

---

documentation/CartographicMap.json
documentation/schema.yaml
src/main/java/no/unit/nva/model/contexttypes/Cartograph.java
src/main/java/no/unit/nva/model/contexttypes/PublicationContext.java
src/main/java/no/unit/nva/model/instancetypes/PublicationInstance.java
src/main/java/no/unit/nva/model/instancetypes/cartographic/CartographicMap.java
src/test/java/no/unit/nva/PublicationTest.java
src/test/java/no/unit/nva/model/ModelTest.java

Adds a ContextType "Cartograph", which means "illustrated map", and a CartographicMap (I imagine "Map.class" might confuse people).
Otherwise, this is just empty for now.

Add CartographicMap and Cartograph

---

documentation/BookAnthology.json
documentation/BookMonograph.json
documentation/CartographicMap.json
documentation/ChapterArticle.json
documentation/DegreeBachelor.json
documentation/DegreeMaster.json
documentation/DegreePhd.json
documentation/FeatureArticle.json
documentation/JournalArticle.json
documentation/JournalCorrigendum.json
documentation/JournalLeader.json
documentation/JournalLetter.json
documentation/JournalReview.json
documentation/JournalShortCommunication.json
documentation/MusicNotation.json
documentation/OtherStudentWork.json
documentation/ReportPolicy.json
documentation/ReportResearch.json
documentation/ReportWorkingPaper.json
documentation/schema.yaml
src/main/java/no/unit/nva/PublicationMapper.java
src/main/java/no/unit/nva/WithMetadata.java
src/main/java/no/unit/nva/api/CreatePublicationRequest.java
src/main/java/no/unit/nva/api/PublicationResponse.java
src/main/java/no/unit/nva/api/UpdatePublicationRequest.java
src/main/java/no/unit/nva/model/Publication.java
src/test/java/no/unit/nva/PublicationMapperTest.java
src/test/java/no/unit/nva/PublicationTest.java
src/test/java/no/unit/nva/model/ModelTest.java
src/test/java/no/unit/nva/model/util/PublicationGenerator.java

Made the project field an array.

Np 1743 allow multiple projects

---

documentation/ReportBasic.json
src/main/java/no/unit/nva/model/instancetypes/report/ReportBasic.java
src/test/java/no/unit/nva/PublicationTest.java
src/test/java/no/unit/nva/model/ModelTest.java

Moves the Report instance type to ReportBasic

Add report basic tests

---

documentation/BookAnthology.json
documentation/BookMonograph.json
documentation/CartographicMap.json
documentation/ChapterArticle.json
documentation/DegreeBachelor.json
documentation/DegreeMaster.json
documentation/DegreePhd.json
documentation/FeatureArticle.json
documentation/JournalArticle.json
documentation/JournalCorrigendum.json
documentation/JournalLeader.json
documentation/JournalLetter.json
documentation/JournalReview.json
documentation/JournalShortCommunication.json
documentation/MusicNotation.json
documentation/OtherStudentWork.json
documentation/ReportPolicy.json
documentation/ReportResearch.json
documentation/ReportWorkingPaper.json
documentation/schema.yaml
src/main/java/no/unit/nva/model/instancetypes/journal/JournalCorrigendum.java
src/test/java/no/unit/nva/model/ModelTest.java

Adds a URI reference to the JournalCorrigendum to refer to the article for which the corrigendum is a corrigendum

Add field corrigendumFor

---

documentation/ReportBasic.json
documentation/schema.yaml
src/main/java/no/unit/nva/model/instancetypes/PublicationInstance.java
src/test/java/no/unit/nva/model/instancetypes/report/ReportBasicTest.java

Add report basic where it was overlooked

---

documentation/DegreeBachelor.json
documentation/DegreeMaster.json
documentation/DegreePhd.json
documentation/OtherStudentWork.json
documentation/schema.yaml
src/main/java/no/unit/nva/model/instancetypes/degree/DegreeBachelor.java
src/main/java/no/unit/nva/model/instancetypes/degree/DegreeBase.java
src/main/java/no/unit/nva/model/instancetypes/degree/DegreeMaster.java
src/main/java/no/unit/nva/model/instancetypes/degree/DegreePhd.java
src/main/java/no/unit/nva/model/instancetypes/degree/OtherStudentWork.java
src/test/java/no/unit/nva/model/ModelTest.java

Student work naturally has a submitted date, which needs to be supported in Brage Import and NVA (at some point)

Add submitted date

---

build.gradle
documentation/JournalInterview.json
documentation/schema.yaml
src/main/java/no/unit/nva/PublicationMapper.java
src/main/java/no/unit/nva/model/instancetypes/PublicationInstance.java
src/main/java/no/unit/nva/model/instancetypes/journal/JournalInterview.java
src/test/java/no/unit/nva/PublicationTest.java
src/test/java/no/unit/nva/model/ModelTest.java
src/test/java/provider/InstanceTypeProvider.java

Adds a new JournalInterview instance type
- update so commons latest version is applied
- move instance supplier to its own class

Add journal interview instance type

---

src/main/java/no/unit/nva/model/Role.java

Adding contributor types, these are not used at present, I do not know how they will be used, if at all, and I am not sure what to test, but they are available as per instruction

Add additional contributor types

---

documentation/CartographicMap.json
documentation/ChapterArticle.json
documentation/schema.yaml
src/main/java/no/unit/nva/model/instancetypes/chapter/ChapterArticle.java
src/test/java/no/unit/nva/model/ModelTest.java
src/test/java/no/unit/nva/model/instancetypes/InstanceTest.java
src/test/java/no/unit/nva/model/instancetypes/chapter/ChapterArticleTest.java

Remove
- textbook content from ChapterArticle as this is in the referenced context
- tidy up unused constants

Remove textbook from chapter article

---

documentation/BookAbstracts.json
documentation/schema.yaml
src/main/java/no/unit/nva/model/instancetypes/PublicationInstance.java
src/main/java/no/unit/nva/model/instancetypes/book/BookAbstracts.java
src/test/java/no/unit/nva/PublicationTest.java
src/test/java/no/unit/nva/model/ModelTest.java
src/test/java/provider/InstanceTypeProvider.java

Adds book of abstracts instance type

Add book of abstracts instance type

---

build.gradle
jitpack.yml

Originally wanted to fix wrong Java version choice in Jitpack, but ended up building the artifacts in a controlled and repricable way and publishing them in Jitpack. 
Publishing to Jitpack is not meant as a replacement for Maven Central. It is meant to use during development

Publish own artifact to jitpack

---

.github/workflows/maven-central.yml
build.gradle
src/main/java/no/unit/nva/model/Publication.java
src/test/java/no/unit/nva/model/PublicationTest.java

This means that "develop" branch should be deleted and merge only to the main branch. I do not see the reason to have the develop branch since we are deploying in production based on the develop branch here.

Publish to maven central

---

build.gradle

Bumping version for testing of publishing to maven central

Update publishing config

---

build.gradle
documentation/schema.yaml
src/main/java/no/unit/nva/model/contexttypes/BookSeries.java
src/main/java/no/unit/nva/model/contexttypes/UnconfirmedSeries.java
src/test/java/no/unit/nva/model/contexttypes/BookTest.java
src/test/java/no/unit/nva/model/contexttypes/DegreeTest.java
src/test/java/no/unit/nva/model/contexttypes/ReportTest.java
src/test/java/no/unit/nva/model/contexttypes/UnconfirmedSeriesTest.java
src/test/java/no/unit/nva/model/util/IssnGenerator.java
src/test/java/no/unit/nva/model/util/PublicationGenerator.java
src/test/java/no/unit/nva/utils/RandomPublicationContexts.java

This PR adds ISSN field to Unconfirmed series, because Cristin has such entries. 
Changes:
* Add "issn" field and parameter to UnconfirmedSeries constructor.
* Make the constructor that accepts only a title a static method to avoid throwing an InvalidIssnException that cannot occur.
* Added a randomIssn() and randomInvalidIssn() method for creating random ISSNs

add issn to UnconfirmedSeries

---

build.gradle
src/main/java/no/unit/nva/model/Contributor.java

- removes pointless javadoc
- removes stray constant

Small fixes to contributor

---

documentation/ArtisticDesignClothingDesign.json
documentation/ArtisticDesignExhibition.json
documentation/ArtisticDesignGraphicDesign.json
documentation/ArtisticDesignIllustration.json
documentation/ArtisticDesignInteractionDesign.json
documentation/ArtisticDesignInteriorDesign.json
documentation/ArtisticDesignLightDesign.json
documentation/ArtisticDesignOther.json
documentation/ArtisticDesignProductDesign.json
documentation/ArtisticDesignServiceDesign.json
documentation/ArtisticDesignWebDesign.json
documentation/schema.yaml
nva-datamodel-java/src/main/java/no/unit/nva/model/contexttypes/Book.java
nva-datamodel-java/src/test/java/no/unit/nva/model/contexttypes/BookTest.java

No idea why all the json files where included but they became modified one way or another, same goes for the schema.yaml file

NP-3204 Fix isbn validator.

---

documentation/schema.yaml
nva-datamodel-java/src/main/java/no/unit/nva/model/instancetypes/artistic/ArchitectureOutput.java
nva-datamodel-java/src/main/java/no/unit/nva/model/instancetypes/artistic/realization/MentionInPublication.java
nva-datamodel-testutils/src/main/java/no/unit/nva/model/testing/PublicationInstanceBuilder.java

- Adds a somewhat strange "mention in publication", which may be either a mention in a publication, or an actual publication
- It is *not* a publication in NVA terms (although NVA may encompass the publication in some other resource), but a published-in-the-traditional-sense publication
- I am not sure why the mention-in-publication publication is not just a URI, but it is not — I guess because it may include a sidenote in a magazine

Add mention in publication

---

nva-datamodel-java/src/main/java/no/unit/nva/model/instancetypes/artistic/realization/Award.java
nva-datamodel-java/src/main/java/no/unit/nva/model/instancetypes/artistic/realization/Competition.java
nva-datamodel-java/src/main/java/no/unit/nva/model/instancetypes/artistic/realization/Exhibition.java
nva-datamodel-java/src/main/java/no/unit/nva/model/instancetypes/artistic/realization/MentionInPublication.java

- Adds type info
- Regenerate equals/hash to include sequence

Fix annotated code

---

buildSrc/src/main/groovy/nvadatamodel.java-conventions.gradle
gradle/libs.versions.toml
nva-datamodel-java/src/main/java/no/unit/nva/PublicationMapper.java
nva-datamodel-java/src/main/java/no/unit/nva/api/PublicationContext.java
nva-datamodel-java/src/main/java/no/unit/nva/api/PublicationResponse.java

- uses the json-ld context provided by the publication object

Use new json-ld context

---

buildSrc/src/main/groovy/nvadatamodel.java-conventions.gradle
nva-datamodel-java/src/main/java/no/unit/nva/model/contexttypes/Series.java

- Regex validation code smell updated to mask non-production subdomain

Mask non-production element of URI

---

buildSrc/src/main/groovy/nvadatamodel.java-conventions.gradle
nva-datamodel-java/src/main/java/no/unit/nva/model/PublicationStatus.java

Høres denne enumen ok ut?
Se også forøvrig slack https://sikt-no.slack.com/archives/CN005AQCE/p1673430958877679

NP-28714-possible-to-delete-published-publications, added enum

---

nva-datamodel-java/src/main/java/no/unit/nva/model/instancetypes/artistic/UnconfirmedPublisherMigrator.java
nva-datamodel-java/src/main/java/no/unit/nva/model/instancetypes/artistic/architecture/realization/Award.java
nva-datamodel-java/src/main/java/no/unit/nva/model/instancetypes/artistic/architecture/realization/Competition.java
nva-datamodel-java/src/main/java/no/unit/nva/model/instancetypes/artistic/architecture/realization/Exhibition.java
nva-datamodel-java/src/main/java/no/unit/nva/model/instancetypes/artistic/architecture/realization/MentionInPublication.java
nva-datamodel-java/src/main/java/no/unit/nva/model/instancetypes/artistic/design/realization/Venue.java
nva-datamodel-java/src/main/java/no/unit/nva/model/instancetypes/artistic/film/realization/Broadcast.java
nva-datamodel-java/src/main/java/no/unit/nva/model/instancetypes/artistic/film/realization/CinematicRelease.java
nva-datamodel-java/src/main/java/no/unit/nva/model/instancetypes/artistic/film/realization/OtherRelease.java
nva-datamodel-java/src/main/java/no/unit/nva/model/instancetypes/artistic/music/AudioVisualPublication.java
nva-datamodel-java/src/main/java/no/unit/nva/model/instancetypes/artistic/music/MusicScore.java
nva-datamodel-java/src/main/java/no/unit/nva/model/instancetypes/artistic/performingarts/realization/PerformingArtsVenue.java
nva-datamodel-java/src/main/java/no/unit/nva/model/instancetypes/realization/WithSequence.java
nva-datamodel-java/src/test/java/no/unit/nva/MigrationTestingUnconfirmedPublisher.java

Migrates publishers from strings to UnconfirmedPublishers

Migrate publishers from strings

---

buildSrc/src/main/groovy/nvadatamodel.java-conventions.gradle
nva-datamodel-java/src/main/java/no/unit/nva/model/instancetypes/artistic/UnconfirmedPublisherMigrator.java
nva-datamodel-java/src/main/java/no/unit/nva/model/instancetypes/artistic/architecture/realization/Award.java
nva-datamodel-java/src/main/java/no/unit/nva/model/instancetypes/artistic/architecture/realization/Competition.java
nva-datamodel-java/src/main/java/no/unit/nva/model/instancetypes/artistic/architecture/realization/Exhibition.java
nva-datamodel-java/src/main/java/no/unit/nva/model/instancetypes/artistic/architecture/realization/MentionInPublication.java
nva-datamodel-java/src/main/java/no/unit/nva/model/instancetypes/artistic/design/realization/Venue.java
nva-datamodel-java/src/main/java/no/unit/nva/model/instancetypes/artistic/film/realization/Broadcast.java
nva-datamodel-java/src/main/java/no/unit/nva/model/instancetypes/artistic/film/realization/CinematicRelease.java
nva-datamodel-java/src/main/java/no/unit/nva/model/instancetypes/artistic/film/realization/OtherRelease.java
nva-datamodel-java/src/main/java/no/unit/nva/model/instancetypes/artistic/music/AudioVisualPublication.java
nva-datamodel-java/src/main/java/no/unit/nva/model/instancetypes/artistic/music/MusicScore.java
nva-datamodel-java/src/main/java/no/unit/nva/model/instancetypes/artistic/performingarts/realization/PerformingArtsVenue.java
nva-datamodel-java/src/main/java/no/unit/nva/model/instancetypes/realization/WithSequence.java
nva-datamodel-java/src/main/java/no/unit/nva/model/time/Instant.java
nva-datamodel-java/src/main/java/no/unit/nva/model/time/Period.java
nva-datamodel-java/src/main/java/no/unit/nva/model/time/Time.java
nva-datamodel-java/src/test/java/no/unit/nva/MigrationTestingUnconfirmedPublisher.java
nva-datamodel-java/src/test/java/no/unit/nva/model/time/TimeMigrationTest.java

Naïve migration, to be removed in next PR — once applied

Add temporary migration

---

buildSrc/src/main/groovy/nvadatamodel.java-conventions.gradle
nva-datamodel-java/src/main/java/no/unit/nva/model/instancetypes/PublicationInstance.java

- Use Jackson type annotations to support PopSciMonograph

Add popular science monograph to known subtypes

---

documentation/ConferenceReport.json
nva-datamodel-java/src/main/java/no/unit/nva/model/instancetypes/PublicationInstance.java
nva-datamodel-java/src/main/java/no/unit/nva/model/instancetypes/report/ConferenceReport.java
nva-datamodel-testutils/src/main/java/no/unit/nva/model/testing/PublicationContextBuilder.java
nva-datamodel-testutils/src/main/java/no/unit/nva/model/testing/PublicationInstanceBuilder.java

- Adds conference report type
- Is a simple subtype of report
- Serializes/Deserializes
- Included auto-generated JSON in documentation for simple reference

Add Conference report

---

buildSrc/src/main/groovy/nvadatamodel.java-conventions.gradle

- bumps version
- Adds changes from previous merges (literary arts stuff)

Bump version to collect changes from previous commits

---

buildSrc/src/main/groovy/nvadatamodel.java-conventions.gradle
nva-datamodel-java/src/main/java/no/unit/nva/model/associatedartifacts/file/File.java

Changed uri for rights reserved.

change uri for rightsreserved license.

---

buildSrc/src/main/groovy/nvadatamodel.java-conventions.gradle
nva-datamodel-java/src/main/resources/publicationContext.json
nva-datamodel-java/src/main/resources/publicationContextDeprecated.json

- Adds source as a uri to context object

Add source to context object

---

buildSrc/src/main/groovy/nvadatamodel.java-conventions.gradle
nva-datamodel-java/src/main/java/no/unit/nva/model/contexttypes/Journal.java
nva-datamodel-java/src/main/java/no/unit/nva/model/contexttypes/Publisher.java
nva-datamodel-java/src/main/java/no/unit/nva/model/contexttypes/Series.java
nva-datamodel-java/src/main/java/no/unit/nva/model/contexttypes/utils/MigrateChannelIdUtil.java
nva-datamodel-java/src/test/java/no/unit/nva/utils/MigratePublicationChannelIdTestUtils.java

Np 44910 publication channel migration prod
